### PR TITLE
RavenDB-3088 added the ability to limit number of replicated items from ...

### PR DESCRIPTION
**Pull request by ppekrol**
...destination server (Raven/Replication/MaxNumberOfItemsToReceiveInSingleBatch)

### CODE REVIEW

**Comment by ayende** [comment]
Why was closed?
Also, what is the logic behind this feature?

*Hibernating Rhinos Ltd  *

Oren Eini\* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ppekrol** [comment]
Ups, I was showing a friend how to create a PR from one branch to another inside same repository

**Comment by ayende** [comment]
Oh, I saw the issue about that, yes, that is correct, we don't want to
increase the replication size without any limit.

Also, we need to limit it so any error would cause the replication batch
size to revert to default.
And the destination server should indicate whatever it is _willing_ to
accept more items. And we need to make this determination on the fly.
I think that we should say that we can accept more items in the next
request if we have at least double the min memory required for raising
batch available.

*Hibernating Rhinos Ltd  *

Oren Eini\* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ppekrol** [comment]
I will answer you here: https://github.com/ayende/ravendb/pull/1827

**Pull request closed without merging**
